tap "cantino/mcfly"
tap "dopplerhq/cli"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "superfly/tap"
brew "antigen"
brew "libevent"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "asdf"
brew "augeas"
brew "gettext"
brew "libffi"
brew "pixman"
brew "calc"
brew "camlp5"
brew "certbot"
brew "cmake"
brew "curl"
brew "deno"
brew "dict"
brew "direnv"
brew "docker-compose", link: false
brew "little-cms2"
brew "ghostscript"
brew "epstool"
brew "erlang"
brew "exiftool"
brew "gawk"
brew "gdk-pixbuf"
brew "gh"
brew "git"
brew "git-extras"
brew "glpk"
brew "gnu-sed"
brew "gnupg"
brew "pango"
brew "graphicsmagick"
brew "graphviz"
brew "grep"
brew "hashcat"
brew "hdf5"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "ledit"
brew "libicns"
brew "libsvm"
brew "lnav"
brew "mackup"
brew "make"
brew "mas"
brew "openjdk"
brew "maven"
brew "metis"
brew "mysql"
brew "neo4j"
brew "neovim"
brew "nmap"
brew "plotutils"
brew "pyqt@5"
brew "qhull"
brew "texinfo"
brew "octave"
brew "packer"
brew "perl"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "pure"
brew "qt"
brew "pyqt"
brew "python@3.8"
brew "rabbitmq"
brew "raptor"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "sip"
brew "sqlcipher"
brew "subversion"
brew "terraform"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tika"
brew "titan-server"
brew "tldr"
brew "tmux"
brew "tree"
brew "vault"
brew "vim"
brew "wget"
brew "yank"
brew "z"
brew "zookeeper"
brew "zsh"
brew "cantino/mcfly/mcfly"
brew "dopplerhq/cli/doppler"
brew "heroku/brew/heroku"
brew "superfly/tap/flyctl"
cask "1password"
cask "aerial"
cask "alfred"
cask "camo-studio"
cask "cryptomator"
cask "docker"
cask "dotnet-sdk"
cask "dwarf-fortress"
cask "encryptme"
cask "font-fira-code"
cask "font-hack"
cask "font-input"
cask "font-juliamono"
cask "font-monoid"
cask "font-noto-mono"
cask "font-roboto-mono"
cask "font-source-code-pro"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite-no-mail"
cask "imageoptim"
cask "iterm2"
cask "keybase"
cask "kindle"
cask "ksdiff"
cask "loom"
cask "ngrok"
cask "notion"
cask "openemu"
cask "raindropio"
cask "raycast"
cask "rectangle"
cask "sketch"
cask "spotify"
cask "steam"
cask "transmission"
cask "typora"
cask "visual-studio-code"
cask "webtorrent"
cask "xquartz"
mas "1Blocker", id: 1365531024
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Craft", id: 1487937127
mas "DaisyDisk", id: 411643860
mas "Darkroom", id: 953286746
mas "Day One", id: 1055511498
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "Hush", id: 1544743900
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Instapaper Save", id: 1481302432
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "Momentum", id: 1564329434
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Poolsuite FM", id: 1514817810
mas "Save to Raindrop.io", id: 1549370672
mas "Scan Thing", id: 1556313108
mas "Soulver 2", id: 413965349
mas "TextSniper", id: 1528890965
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Transmit", id: 403388562
mas "Xcode", id: 497799835
