tap "cantino/mcfly"
tap "dopplerhq/cli"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "superfly/tap"
brew "antigen"
brew "libevent"
brew "open-mpi"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "asdf"
brew "augeas"
brew "bat"
brew "gettext"
brew "libffi"
brew "pixman"
brew "little-cms2"
brew "binwalk"
brew "calc"
brew "camlp5"
brew "python@3.10"
brew "certbot"
brew "cmake"
brew "openldap"
brew "curl"
brew "deno"
brew "dict"
brew "diff-so-fancy"
brew "direnv"
brew "docker-compose"
brew "ghostscript"
brew "epstool"
brew "erlang"
brew "exiftool"
brew "netpbm"
brew "fltk"
brew "fzf"
brew "gawk"
brew "gdk-pixbuf"
brew "gh"
brew "git"
brew "git-extras"
brew "glpk"
brew "gnu-sed"
brew "guile"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "pango"
brew "gnuplot"
brew "graphicsmagick"
brew "librsvg"
brew "graphviz"
brew "grep"
brew "hashcat"
brew "hdf5"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "ledit"
brew "less"
brew "libarchive"
brew "libicns"
brew "libsvm"
brew "lnav"
brew "mackup"
brew "make"
brew "mas"
brew "openjdk"
brew "maven"
brew "metis"
brew "mysql"
brew "n"
brew "neo4j"
brew "neovim"
brew "nmap"
brew "plotutils"
brew "pstoedit"
brew "pyqt@5"
brew "qhull"
brew "texinfo"
brew "octave"
brew "packer"
brew "perl"
brew "postgresql", restart_service: true
brew "pure"
brew "qt"
brew "pyqt"
brew "python@3.8"
brew "rabbitmq"
brew "raptor"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "ruby-build"
brew "terraform"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tree"
brew "vault"
brew "vim"
brew "wget"
brew "z"
brew "zookeeper"
brew "zoxide"
brew "zsh"
brew "cantino/mcfly/mcfly"
brew "dopplerhq/cli/doppler"
brew "heroku/brew/heroku"
brew "superfly/tap/flyctl"
cask "1password"
cask "1password-cli"
cask "aerial"
cask "airbuddy"
cask "balenaetcher"
cask "brave-browser"
cask "cleanshot"
cask "cryptomator"
cask "docker"
cask "dotnet-sdk"
cask "encryptme"
cask "font-fira-code"
cask "font-hack"
cask "font-input"
cask "font-juliamono"
cask "font-monoid"
cask "font-noto-mono"
cask "font-roboto-mono"
cask "font-source-code-pro"
cask "google-cloud-sdk"
cask "gpg-suite-no-mail"
cask "imageoptim"
cask "iterm2"
cask "keybase"
cask "kindle"
cask "ksdiff"
cask "ledger-live"
cask "loom"
cask "ngrok"
cask "notion"
cask "nova"
cask "raycast"
cask "rectangle"
cask "sketch"
cask "steam"
cask "thingsmacsandboxhelper"
cask "visual-studio-code"
cask "webtorrent"
cask "xquartz"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "Amphetamine", id: 937984704
mas "Craft", id: 1487937127
mas "DaisyDisk", id: 411643860
mas "Dark Noise", id: 1465439395
mas "Darkroom", id: 953286746
mas "Day One", id: 1055511498
mas "Evernote", id: 406056744
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "Matter", id: 1548677272
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Poolsuite FM", id: 1514817810
mas "Scan Thing", id: 1556313108
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
