tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/x11"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/cask"
cask "java"
cask "xquartz"
brew "openssl"
brew "aircrack-ng"
brew "antigen"
brew "augeas"
brew "autoconf"
brew "automake"
brew "gettext"
brew "libffi"
brew "blackbox"
brew "pixman"
brew "calc"
brew "camlp5"
brew "certbot"
brew "chromedriver"
brew "cmake"
brew "coreutils"
brew "wxmac"
brew "spidermonkey"
brew "couchdb"
brew "curl"
brew "dict"
brew "direnv"
brew "elasticsearch", restart_service: true
brew "little-cms2"
brew "ghostscript"
brew "epstool"
brew "exiftool"
brew "git"
brew "git-extras"
brew "glpk"
brew "gnu-sed"
brew "libtool"
brew "graphicsmagick"
brew "graphviz"
brew "hashcat"
brew "hdf5"
brew "heroku"
brew "hub"
brew "zookeeper"
brew "kafka"
brew "kubernetes-cli"
brew "ledit"
brew "libevent"
brew "libicns"
brew "libsvm"
brew "libyaml"
brew "lnav"
brew "logstash"
brew "mackup"
brew "mas"
brew "maven"
brew "metis"
brew "mongodb", restart_service: true
brew "mysql"
brew "neo4j"
brew "neovim"
brew "nmap"
brew "plotutils"
brew "qhull"
brew "octave"
brew "packer"
brew "pango"
brew "peco"
brew "perl"
brew "phantomjs"
brew "qt"
brew "rabbitmq"
brew "raptor"
brew "rbenv"
brew "redis", restart_service: true
brew "rethinkdb"
brew "rpm"
brew "ruby"
brew "sqlcipher", args: ["with-fts"]
brew "stout"
brew "terraform"
brew "texinfo"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tika"
brew "titan-server"
brew "tldr"
brew "tmux"
brew "tree"
brew "vault"
brew "vim"
brew "virtuoso"
brew "wget"
brew "wrk"
brew "yank"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"
cask "aerial"
cask "alfred"
cask "anki"
cask "aquaterm"
cask "arduino"
cask "atom"
cask "backblaze"
cask "beaker-browser"
cask "brave"
cask "dashlane"
cask "dbeaver-community"
cask "docker"
cask "dolphin"
cask "dotnet-sdk"
cask "dropbox"
cask "duet"
cask "dwarf-fortress"
cask "evernote"
cask "firefox"
cask "franz"
cask "freedom"
cask "gephi"
cask "gitup"
cask "google-chrome"
cask "hammerspoon"
cask "imageoptim"
cask "iterm2"
cask "kap"
cask "keepingyouawake"
cask "keybase"
cask "launchrocket"
cask "little-snitch"
cask "minecraft"
cask "ngrok"
cask "openemu"
cask "postgres"
cask "postman"
cask "private-internet-access"
cask "rescuetime"
cask "resilio-sync"
cask "sdl-framework"
cask "sdl-ttf-framework"
cask "sketch"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "textual"
cask "transmission"
cask "tripmode"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "webtorrent"
cask "xscope"
cask "caskroom/drivers/logitech-gaming-software"
cask "caskroom/fonts/font-fira-code"
cask "caskroom/fonts/font-source-code-pro"
mas "1Password", id: 443987910
mas "CloudApp", id: 417602904
mas "DaisyDisk", id: 411643860
mas "GarageBand", id: 682658836
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "Micro Snitch", id: 972028355
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Reeder", id: 880001334
mas "Sip", id: 507257563
mas "Soulver", id: 413965349
mas "The Unarchiver", id: 425424353
mas "Transmit", id: 403388562
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
